### ISSUE TITLE
Not Available.

### ISSUE THREAD

**Issue by H-adorable** [cocodataset/cocodataset.github.io#3]
The site cocodataset.org is not available.
When I visit it, only header & footer of the page is loaded.
Other part of the page is totally blank, and buttons on the header does not worked.

**Comment by nightrome** [comment]
It works for me..

**Comment by H-adorable** [comment]
I'm in Mainland China, maybe that is the reason why the site is not work?
It used to be available in June, 2017.  But unavailable now.

If it can be visited, that would be so helpful to the researcher in Mainland China.

**Comment by pdollar** [comment]
I just checked right now and the dataset is viewable... Can you see if other github hosted sites are accessible? E.g., http://pdollar.github.io/ ?  I'm not sure if the site actually had an outage or if it's just blocked in your area... For the latter there's not much we can do :( 

You may also want to try another browser and make sure Javascript is enabled.

**Comment by H-adorable** [comment]
This site  [http://pdollar.github.io/]( http://pdollar.github.io/ )  is ok.
I'm using chrome, so I don't think the problem is caused by my browser.

I traced the loading process of `cocodata.org`, and found that the site is loading some `.js` from `ajax.googleapi.com` with the red code **pending**. It may be the reason why site is not available.

SAD

Is there any possible to replace googleapis.com to other site?

**Comment by H-adorable** [comment]
Here is my solution.
Using firfox with the extension **goorelacer**, which will redirect googleapis.com

Then the site is OK.

**Comment by pdollar** [comment]
Ok thanks for posting your solution... That does seem indeed frustrating. But I am glad you found a way to access the content.
