### ISSUE TITLE
Can't explore dataset with Google Chrome

### ISSUE THREAD

**Issue by KyryloAntoshyn** [cocodataset/cocodataset.github.io#52]
Hi! I am using Google Chrome, but I can't explore the dataset (I can't see images):
![image](https://user-images.githubusercontent.com/26432700/97459386-65200580-1944-11eb-86a6-2e145d63febd.png)

If I go to the console I see a lot of certificate errors:
![image](https://user-images.githubusercontent.com/26432700/97459471-7cf78980-1944-11eb-9500-08840916663a.png)

In Edge everything is fine:
![image](https://user-images.githubusercontent.com/26432700/97459636-a4e6ed00-1944-11eb-9c53-716a6be6d33a.png)

Fix it, please! Thanks in advance!

**Comment by Pyrax** [comment]
It's working now.

**Comment by KyryloAntoshyn** [comment]
> It's working now.

Doesn't work actually.

**Comment by Pyrax** [comment]
Since yesterday, the cert is in fact invalid again.

**Comment by KyryloAntoshyn** [comment]
It works fine now.
